### ISSUE TITLE
Installation instructions error

### ISSUE THREAD

**Issue by bulletmark** [mojavelinux/asciidoc-dzslides-backend#6]
I tried to install this backend according to the README but it doesn't make sense because the symlink links the same named dzslides directory over the top of the first clone. I.e.:

```
% ln -s ~-/dzslides .
ln: failed to create symbolic link ‘./dzslides’: File exists
```

Looking at the commit history I realise that it should be created in the first dir so I think you should simplify the instructions to:

```
mkdir -p ~/.asciidoc/backends/
cd ~/.asciidoc/backends/
git clone https://github.com/mojavelinux/asciidoc-dzslides-backend.git dzslides
cd dzslides
git clone https://github.com/mojavelinux/dzslides.git
```

**Comment by mojavelinux** [comment]
Would you be willing to submit a pull request?

Btw, there is a more recent version of the dzslides backend for Asciidoctor at https://github.com/asciidoctor/asciidoctor-backends/blob/master/slim/dzslides/README.adoc. I don't maintain the one for AsciiDoc Python anymore.

**Comment by bulletmark** [comment]
You just need to delete the 2 quoted installation procedures and replace with the commands above. I ran asciidoc with this backend but much prefer the standard slidy output so I immediately deleted my dzslides installation. If you don't want to maintain this anymore then best to delete the repo or at least at a disclaimer to the top of the README and point people to your asciidoctor version.

BTW, I tried a few asciidoctor + slide backends but still think asciidoc + native slidy is the best.

**Comment by mojavelinux** [comment]
Thanks. I went ahead and fixed it. You're correct, that's a lot simpler for people coming along.

I'll add a note to the README about the backend for Asciidoctor. I don't like delete repositories, so I'm going to stick with the note.

> BTW, I tried a few asciidoctor + slide backends but still think asciidoc + native slidy is the best.

Presentation frameworks are a very personal thing. What makes one framework perfect for one person may not fit the needs at all for another. We hope to have more options in Asciidoctor soon. My focus isn't to limit options for people, just get them off AsciiDoc Python :)
